#!/bin/bash


echo "start nuxt project"
# read -p "? Project name:"
echo -n ? Project name:
#入力を受付、その入力を「str」に代入
read projedtName
#結果を表示
echo ${projedtName}
mv ../nuxt-template/ ../${projectName}/
cd ../${projectName}/
# mv nuxt-template/ ${projectName}/
# create env file
# touch .env
#  yarn install
# git init
